name: build-frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: build and publish pages
      run: |
            cd viz
            npm install
            npm run build
            cd dist
            git init
            git add -A
            git commit -m 'deploy github pages'
            git push -f git@github.com:mariloubylr/ci-magic.git main:gh-pages
      shell: bash
