name: build-frontend-pr-pages

on:
  pull_request:

env:
  PR_NUMBER: PR-${{ github.event.number }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: actions/setup-node@main
    - name: build and publish pages
      run: |
            cd frontend
            npm install
            mkdir -p app/dist/${{env.PR_NUMBER}}
            export VUE_APP_BASE=${{env.PR_NUMBER}}
            npm run build -- --dest=app/dist/${{env.PR_NUMBER}}
            cd app/dist
            git config --global init.defaultBranch main
            git config --global user.email "marilou.beyeler@gmail.com"
            git config --global user.name "mariloubylr"
            git init
            git add -A
            git commit -m 'deploy github pages ${{env.PR_NUMBER}}'
            
            if [[ $(git diff origin/gh-pages) ]]
            then
              echo "Remote changes are overwritten by local changes."
              git push -qf origin gh-pages:gh-pages
            else
                echo "No new changes"
            fi       
      shell: bash
