name: build-frontend-pr-pages

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: actions/setup-node@main
    - name: build and publish pages
      run: |
            cd frontend
            npm install
            mkdir -p app/dist/pr
            export VUE_APP_BASE=pr
            npm run build -- --dest=app/dist/pr
            cd app/dist
            git clone --branch gh-pages https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git
            git config --local advice.skippedCherryPicks false 
            git config --global user.email "marilou.beyeler@gmail.com"
            git config --global user.name "mariloubylr"
            git add -A
            git commit -m 'deploy github pages pr'
            
            git push -f https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git main:gh-pages
      shell: bash
