name: build-frontend-pr-pages

on:
  pull_request:

env:
  PR_NUMBER: PR-${{ github.event.number }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: actions/setup-node@main
    - name: build and publish pages
      run: |
            cd frontend
            npm install
            mkdir -p app/dist/$PR_NUMBER
            export VUE_APP_BASE=$PR_NUMBER
            npm run build -- --dest=app/dist/${{PR_NUMBER}}
            cd app/dist
            git config --global init.defaultBranch main
            git config --global user.email "marilou.beyeler@gmail.com"
            git config --global user.name "mariloubylr"
            git init
            git add -A
            git commit -m 'deploy github pages $PR_NUMBER'
            
            git push -f https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git main:gh-pages
      shell: bash
