name: build-frontend-pr-pages

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: actions/setup-node@main
    - name: build and publish pages
      run: |
            cd frontend
            npm install
            mkdir -p app/dist/pr
            npm run build -- --dest=/app/dist/pr
            cd dist
            git config --global init.defaultBranch main
            git config --global user.email "marilou.beyeler@gmail.com"
            git config --global user.name "mariloubylr"
            git init
            git add -A
            git commit -m 'deploy github pages'
            
            git push -f https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git main:gh-pages
      shell: bash
