name: build-frontend-main

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: actions/setup-node@main
    - name: build and publish pages
      run: |
            cd frontend
            npm install
            mkdir -p app/dist/prod
            export VUE_APP_BASE=prod
            git config --global user.email "marilou.beyeler@gmail.com"
            git config --global user.name "mariloubylr"
            git clone --branch gh-pages https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git app/dist
            cd app/dist
            ls
            npm run build -- --dest=app/dist/prpd
            git config --local advice.skippedCherryPicks false 
            git add -A
            git commit -m 'deploy github pages prod'
            
            git push -f https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git main:gh-pages
      shell: bash
