name: build-frontend-pr-pages

on:
  pull_request:

env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: actions/setup-node@main
    - name: build and publish pages
      run: |
            cd frontend
            git config --local advice.skippedCherryPicks false 
            git clone --branch gh-pages https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git app/dist
            npm install
            export VUE_APP_BASE=${{env.PR_NUMBER}}
            npm run build -- --dest=app/dist/${{env.PR_NUMBER}}
            cd app/dist
            git config --global user.email "marilou.beyeler@gmail.com"
            git config --global user.name "mariloubylr"
            git add -A
            git commit -m "deploy github pages ${{env.PR_NUMBER}}"
            
            git push -f https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git gh-pages:gh-pages
      shell: bash
