name: build-frontend-pr-pages

on:
  pull_request:

env:
  PR_NUMBER: PR-${{ github.event.number }}
  BUILD_DIR: app/dist
  GITHUB_URL: https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - uses: actions/setup-node@main
    - name: build and publish pages
      run: |
            cd frontend
            git clone --branch gh-pages ${{env.GITHUB_URL}} ${{env.BUILD_DIR}}
            cd ${{env.BUILD_DIR}}
            ls
            mkdir -p ${{env.PR_NUMBER}}
            export VUE_APP_BASE=${{env.PR_NUMBER}}
            npm run build -- --dest= ${{env.PR_NUMBER}}

            git config --global user.email "marilou.beyeler@gmail.com"
            git config --global user.name "mariloubylr"
            git add -A
            git commit -m 'deploy github pages ${{env.PR_NUMBER}}'
            
            git push -qf ${{env.GITHUB_URL}} gh-pages:gh-pages
     
      shell: bash
