name: run data fetching job

on: 
  push:
    branches:
      - main
  workflow_run:
    workflows: ["build-frontend"]
    branches: [main]
    types: 
      - completed
  schedule:
    - cron: '*/6 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@main # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install python

      - run: |
          cd backend
          ls
        shell: bash

      - name: install python packages
        run: |
          python -m pip install --upgrade pip

      - name: execute python script # run main.py
        run: |
          python backend/fetch_data.py data_dir
          ls

      - name: Copy data to gh-pages branch
        run: |
          mkdir -p temp_build
          cd temp_build
          ls
          git init -q --initial-branch='gh-pages'
          git remote add origin https://github.com/mariloubylr/ci-magic.git
          git config --global user.email "marilou.beyeler@gmail.com"
          git config --global user.name "mariloubylr"
          git config --local advice.skippedCherryPicks false # Disable messages to include skipped commits
          git pull -q origin gh-pages --rebase -X theirs > /dev/null


          ls
          mkdir data_dir
          cp ../data_dir/* data_dir/

          git add -A
          git status
          git commit -qm "update data"
          git push -qf https://mariloubylr:${{ secrets.GITHUB_TOKEN }}@github.com/mariloubylr/ci-magic.git gh-pages:gh-pages
        shell: bash
  
        